# Site settings
title: '万龙华的博客'
email: longhuawan@gmail.com
description: '个人博客,技术相关(JAVA|算法|数据库|Linux|DM)'
logo_location: "http://q.qlogo.cn/headimg_dl?bs=qq&dst_uin=247816604&src_uin=www.feifeiboke.com&fid=blog&spec=100"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

paginate: 8
paginate_path: "/blog/page:num/"
# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#Other Global Configuration
exclude: ['README.md']
